### ISSUE TITLE
Some misaligned text in localization (for example russian)

### ISSUE THREAD

**Issue by CfYz-R** [FarGroup/Far-NetBox#41]
![image](https://github.com/FarGroup/Far-NetBox/assets/17078006/a5ba24dd-49f3-459f-b80e-a30714fa5648)

![image](https://github.com/FarGroup/Far-NetBox/assets/17078006/a22862c7-80cd-412b-867f-81c7ac46a02f)

Modifying language files doesn't work...

**Comment by CfYz-R** [comment]
About window has the same issue even in default English language...

**Comment by yulian5** [comment]
The problem here is that the width for all Dialogs I checked is hard-coded.

I made a fix for 2 mentioned dialogs 
[231218.NetBox.patch](https://github.com/FarGroup/Far-NetBox/files/13710018/231218.NetBox.patch)
and then I found that all dialogs should be fixed so I stopped here.

I think the best approach will be to pass the width from TFarText to parent like TFarDialog and calculate minimum width already inside parent dialog. So I think it's will be fine to apply provided patch for mentioned 2 dialogs and then I proceed with more improvements for all other dialogs.

I tested fixes with all 3 languages for NetBox, looks fine. For "About" dialog there is an extra space on the right side, not clear where it come from. I checked a few dialogs from Far Manager, some of then also have that extra space on the right.

Alex,

I didn't provide any changelog changes or version changes. Please, let me know, If I need to.

I see that NetBox actually needs a lot of work.

**Comment by yulian5** [comment]
Do I need to create a pull request instead of posting a patch?

**Comment by yulian5** [comment]
The same problem here: original screenshots from @CfYz-R are not visible. I found in some comments that it may be related to the user's access rights to the repo. And I can see some other images from another members.

**Comment by alabuzhev** [comment]
Moved to https://github.com/michaellukashov/Far-NetBox/issues/395
